import test from 'node:test'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import { mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { inspectWindowsReadiness, verifyWindowsReadiness } from '../lib/windows-readiness-proof.mjs'
const sha = (value) => createHash('sha256').update(value).digest('hex'); const MACHINE = sha('opaque-machine'); const ENDPOINT = sha('https://api.example.invalid')
const observation = () => ({ schemaVersion: 1, subject: { machineIdSha256: MACHINE, snapshotRevision: 'snapshot-001' }, collectedAt: '2026-08-14T09:00:00.000Z', windows: { productType: 'server', arch: 'x64', build: 26100, pendingReboot: false }, runtime: { nodeVersion: '22.18.0', dshVersion: '0.1.0-rc.6', powerShell: { edition: 'Core', version: '7.5.2', languageMode: 'ConstrainedLanguage' } }, policy: { wdac: 'enforced', appLocker: 'audit', defender: 'active', executionPolicy: 'all_signed', credentialGuard: 'enabled', tls12: true }, filesystem: { longPathsEnabled: true, atomicRenameProbe: true, workspaceAcl: 'restricted', tempAcl: 'restricted', symlinkPolicy: 'denied' }, service: { session: 'non_interactive', identityClass: 'managed_service', profileWritable: true, recoveryConfigured: true }, storage: { workspaceFreeBytes: 10_000_000_000, tempFreeBytes: 2_000_000_000 }, connectivity: [{ id: 'deepseek_api', endpointSha256: ENDPOINT, status: 'reachable', tls: 'valid', proxy: 'managed' }] })
function requirements() { return { evaluationTime: '2026-08-14T09:05:00.000Z', maxAgeSeconds: 600, windows: { allowedProductTypes: ['server'], allowedArchitectures: ['x64'], minBuild: 22000, requireNoPendingReboot: true }, runtime: { minNodeMajor: 22, minPowerShellMajor: 7, allowedPowerShellEditions: ['Core'], allowedLanguageModes: ['ConstrainedLanguage', 'FullLanguage'], allowedDshVersions: ['0.1.0-rc.6'] }, policy: { allowedWdac: ['enforced', 'audit'], allowedAppLocker: ['enforced', 'audit'], allowedDefender: ['active'], allowedExecutionPolicy: ['all_signed', 'remote_signed'], allowedCredentialGuard: ['enabled'], requireTls12: true }, filesystem: { requireLongPaths: true, requireAtomicRename: true, allowedWorkspaceAcl: ['restricted'], allowedTempAcl: ['restricted'], allowedSymlinkPolicy: ['denied', 'allowed'] }, service: { allowedSessions: ['non_interactive'], allowedIdentityClasses: ['managed_service', 'standard_user'], requireProfileWritable: true, requireRecoveryConfigured: true }, storage: { minWorkspaceFreeBytes: 5_000_000_000, minTempFreeBytes: 1_000_000_000 }, connectivity: [{ id: 'deepseek_api', endpointSha256: ENDPOINT, allowedStatus: ['reachable'], allowedTls: ['valid'], allowedProxy: ['managed', 'direct'] }] } }
async function writeJson(file, value) { const body = `${JSON.stringify(value, null, 2)}\n`; await writeFile(file, body); return sha(body) }
async function fixture(mutator = () => {}) { const root = await mkdtemp(join(tmpdir(), 'windows-readiness-proof-')); const observed = observation(); const required = requirements(); mutator(observed, required); const observedSha = await writeJson(join(root, 'observation.json'), observed); const manifest = { schemaVersion: 1, proofId: 'managed-windows', subject: { machineIdSha256: MACHINE, snapshotRevision: 'snapshot-001' }, observation: { path: 'observation.json', sha256: observedSha }, requirements: required }; await writeJson(join(root, 'manifest.json'), manifest); return { root, observed, manifest } }
async function cleanup(root) { await rm(root, { recursive: true, force: true }) }
test('verifies a sanitized managed Windows observation', async () => { const f = await fixture(); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(result.status, 'verified'); assert.equal(result.modifiesHost, false); assert.equal(result.controls.length, 26); assert.equal(sha(await readFile(join(f.root, result.artifact.path))), result.artifact.sha256) } finally { await cleanup(f.root) } })
test('fails closed on stale or future snapshots', async () => { const f = await fixture((_, r) => { r.evaluationTime = '2026-08-14T10:00:00.000Z' }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(result.status, 'failed'); assert.equal(result.controls.find(({ id }) => id === 'snapshot_freshness').reasonCode, 'age_exceeded') } finally { await cleanup(f.root) } })
test('reports Windows build and pending reboot gaps', async () => { const f = await fixture((o) => { o.windows.build = 19045; o.windows.pendingReboot = true }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.ok(result.disclosure.gapControlIds.includes('windows_build')); assert.ok(result.disclosure.gapControlIds.includes('pending_reboot')) } finally { await cleanup(f.root) } })
test('reports Node, DSH and PowerShell runtime gaps', async () => { const f = await fixture((o) => { o.runtime.nodeVersion = '20.0.0'; o.runtime.dshVersion = '0.0.9'; o.runtime.powerShell.version = '5.1.0'; o.runtime.powerShell.edition = 'Desktop' }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.ok(['node_runtime', 'dsh_runtime', 'powershell_runtime'].every((id) => result.disclosure.gapControlIds.includes(id))); assert.ok(!JSON.stringify(result).includes('0.1.0-rc.6')) } finally { await cleanup(f.root) } })
test('reports policy posture without changing policy', async () => { const f = await fixture((o) => { o.policy.wdac = 'off'; o.policy.defender = 'inactive'; o.policy.executionPolicy = 'bypass'; o.policy.credentialGuard = 'disabled'; o.policy.tls12 = false }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(result.modifiesHost, false); assert.ok(['policy_wdac', 'policy_defender', 'policy_execution_policy', 'policy_credential_guard', 'policy_tls12'].every((id) => result.disclosure.gapControlIds.includes(id))) } finally { await cleanup(f.root) } })
test('reports filesystem and ACL gaps', async () => { const f = await fixture((o) => { o.filesystem.longPathsEnabled = false; o.filesystem.atomicRenameProbe = false; o.filesystem.workspaceAcl = 'broad'; o.filesystem.tempAcl = 'unknown'; o.filesystem.symlinkPolicy = 'unknown' }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.ok(result.disclosure.gapControlIds.filter((id) => id.startsWith('filesystem_')).length === 5) } finally { await cleanup(f.root) } })
test('reports non-interactive service and storage gaps', async () => { const f = await fixture((o) => { o.service.session = 'interactive'; o.service.identityClass = 'local_system'; o.service.profileWritable = false; o.service.recoveryConfigured = false; o.storage.workspaceFreeBytes = 1; o.storage.tempFreeBytes = 1 }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.ok(['service_session', 'service_identity', 'service_profile', 'service_recovery', 'storage_workspace', 'storage_temp'].every((id) => result.disclosure.gapControlIds.includes(id))) } finally { await cleanup(f.root) } })
test('binds connectivity by opaque endpoint hash and policy', async () => { const f = await fixture((o) => { o.connectivity[0].endpointSha256 = sha('other'); o.connectivity[0].status = 'blocked'; o.connectivity[0].tls = 'invalid' }); try { const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); const endpoint = result.controls.find(({ id }) => id === 'connectivity_deepseek_api'); assert.equal(endpoint.status, 'gap'); assert.equal(endpoint.reasonCode, 'endpoint_identity_mismatch'); assert.ok(!JSON.stringify(result).includes('https://')) } finally { await cleanup(f.root) } })
test('discloses stale and missing observation evidence', async () => { const f = await fixture(); try { f.observed.windows.pendingReboot = true; await writeJson(join(f.root, 'observation.json'), f.observed); let result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(result.disclosure.staleObservation, true); f.manifest.observation.path = 'missing.json'; f.manifest.observation.sha256 = '0'.repeat(64); await writeJson(join(f.root, 'manifest.json'), f.manifest); result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts2' }); assert.equal(result.disclosure.missingObservation, true) } finally { await cleanup(f.root) } })
test('rejects secret and user-identity shaped observation fields', async () => { const f = await fixture(); try { f.observed.secret = 'NEVER_ECHO_THIS'; f.manifest.observation.sha256 = await writeJson(join(f.root, 'observation.json'), f.observed); await writeJson(join(f.root, 'manifest.json'), f.manifest); const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(result.disclosure.rejectedObservation, true); assert.ok(!JSON.stringify(result).includes('NEVER_ECHO_THIS')) } finally { await cleanup(f.root) } })
test('rejects traversal and symlink manifests and never returns the observation body', async () => { const f = await fixture(); try { await assert.rejects(() => inspectWindowsReadiness({ workspaceRoot: f.root, manifestPath: '../manifest.json' }), { code: 'UNSAFE_PATH' }); await symlink(join(f.root, 'manifest.json'), join(f.root, 'linked.json')); await assert.rejects(() => inspectWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'linked.json' }), { code: 'UNSAFE_PATH' }); const result = await verifyWindowsReadiness({ workspaceRoot: f.root, manifestPath: 'manifest.json', artifactDir: 'artifacts' }); assert.equal(result.returnsObservationBody, false); assert.ok(!JSON.stringify(result).includes('powerShell')) } finally { await cleanup(f.root) } })
